server:
  port: 9000

spring:
  application:
    name: resposta
front:
  url: https://mlr-ashen.vercel.app/
mercadoLivre:
  clientId: ${CLIENT_ID:351292420134820}
  clientSecret: ${CLIENT_SECRET:PvXCcsuDqPylD3WRr5wTxxTrrRXmJWmE}
  baseUrl: https://api.mercadolibre.com/